version: "3.8"
services:
  resty:
    build: ./resty
    container_name: resty
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

  elk:
    build: ./elk
    container_name: elk
    environment:
      - ES_CONNECT_RETRY=300
    networks:
      - backend

#  p0f:
#    build: ./p0f
#    container_name: p0f
#    volumes:
#      - p0f_data:/tmp/p0f
#    network_mode: "host"

#  filebeat:
#    build: ./filebeat
#    container_name: filebeat
#    volumes:
#      - p0f_data:/tmp/p0f
#    networks:
#      - backend

  redis:
    build: ./redis
    container_name: redis
    networks:
      - backend

networks:
  backend:

#volumes:
#  p0f_data:
